package gx.realtime;

public enum EventType {
	COLLABORATOR_JOINED,
	COLLABORATOR_LEFT,
	DOCUMENT_SAVE_STATE_CHANGED,
	REFERENCE_SHIFTED,
	TEXT_DELETED,
	TEXT_INSERTED,
	VALUES_ADDED,
	VALUES_REMOVED,
	VALUES_SET,
	VALUE_CHANGED
}
